# Setup
title:               일단 만든 DEVLOG
tagline:             ' '
description:         '일단 만들어 봤습니다. 이것저것 정리하는 <a href="https://oheunkwon.github.io" target="_blank">DEVLOG</a> 입니다. 테마는 Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://oheunkwon.github.io"
baseurl:             "/"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Oheun Kwon
  url:               https://oheunkwon.github.io
  email:             ddddddddddd@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


category_dir: category/
tag_dir: tag/